version: '3.7'
services:
  restserver:
    image: melashri/sharry:latest
    container_name: sharry
    command: /opt/sharry.conf
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/sharry.conf:/opt/sharry.conf
    depends_on:
      - db
  db:
    image: postgres:14.0
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dbuser-changethat
      - POSTGRES_PASSWORD=dbpass=changethat
      - POSTGRES_DB=dbname-changethat
volumes:
  postgres_data:
